config/routes.rb
Rails.application.routes.draw do
  resources :users, expect: [:new]  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :articles
  # Defines the root path route ("/")
  root "users#new"
  get 'signup', to: 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  has_many :articles 
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i                    
  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 105 }, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end
  
  def show
  end

  def new
    @article = Article.new
  end

  def create 
    @article = Article.new(article_params)
    @article.user = User.first
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to article_path(@article)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
   if @article.update(article_params)
    flash[:notice] = "Article was edited successfully."
    redirect_to @article
   else
    render :edit, status: :unprocessable_entity
   end
  end

  def destroy
    @article.destroy
    redirect_to articles_path , status: :see_other
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description) 
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @articles = @user.articles
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "Welcome to the Blog Page #{@user.username}, you have successfully signed up."
      redirect_to articles_path
    else
      render 'new', status: :unprocessable_entity 
    end
  
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated.."
      redirect_to articles_path
    else
      render 'new', status: :unprocessable_entity 
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80}) 
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded-circle mx-auto d-block mt-4")
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<div class="container">
<% @articles.each do |article|%>
<div class="row justify-content-md-center">
<div class="col-8 mt-4">
<div class="card text-center shadow-lg mb-5 bg-white rounded">
  <div class="card-header font-italic">
    by <%= article.user.username if article.user %>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= link_to article.title, article_path(article) , class: "text-success"%></h5>
    <p class="card-text"><%= truncate(article.description , length: 200)%></p>
    <a href=<%=article_path(article)%> class="btn btn-outline-primary">View</a>
    <a href=<%=edit_article_path(article)%> class="btn btn-outline-info">Edit</a>
    <a href=<%=article_path(article)%> class="btn btn-outline-danger" data-turbo-method="delete"  data-turbo-confirm="Are you sure !!">Delete</a>
  </div>
  <div class="card-footer text-muted">
    <small>Created <%= time_ago_in_words(article.created_at)%> ago , 
    Edited <%= time_ago_in_words(article.updated_at)%> ago. 
    </small>
  </div>
</div>
</div>
</div>
<%end%> 
</div>

app/views/articles/_form.html.erb
<div class="container">
<div class="row justify-content-center">
<div class="col-10">
<%= render "shared/errors", obj: @article %>
<%= form_with model: @article , class: "shadow p-3 mb-3 bg-info rounded" do |form| %>

  <div class="form-group row">
    <%= form.label :title , class: "col-2 col-form-label text-light"%>
    <div class="col-10">
    <%= form.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
    </div>
  </div>

  <div class="form-group row mt-4">
    <%= form.label :description , class: "col-2 col-form-label text-light"%>
    <div class="col-10">
    <%= form.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article"  %>
    </div>
  </div>

  <div class="form-group row mt-4 justify-content-center">
    <%= form.submit class: "btn btn-outline-light btn-lg" %>
  </div>
 
<% end %>
</div>
<%= link_to '[ Cancel and return to articles listing ]' , articles_path , class: "text-info row justify-content-center text-decoration-none"%>
</div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit article</h1>

<%= render 'form'%>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing All Articles</h1>

<%= render 'article'%>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a new article</h1>

<%= render 'form'%>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @article.title%></h2>
<div class="container">
<div class="row justify-content-md-center">
<div class="col-8 mt-4">
<div class="card text-center shadow-lg mb-5 bg-white rounded">
  <div class="card-header font-italic">
    by <%= @article.user.username if @article.user %>
  </div>
  <div class="card-body">
    <div class="card-text text-left"><%= simple_format(@article.description)%></div>
    <a href=<%=edit_article_path(@article)%> class="btn btn-outline-info">Edit</a>
    <a href=<%=article_path(@article)%> class="btn btn-outline-danger" data-turbo-method="delete"  data-turbo-confirm="Are you sure !!">Delete</a>
  </div>
  <div class="card-footer text-muted">
    <small>Created <%= time_ago_in_words(@article.created_at)%> ago , 
    Edited <%= time_ago_in_words(@article.updated_at)%> ago. 
    </small>
  </div>
</div>
</div>
</div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name , msg|%>
<div class="alert alert-success" role="alert" id="my-alert">
  <%= msg %>
</div>  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UdemyRor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%# <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/messages'%>
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="alert alert-danger" role="alert">
  <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved : </h4>
  <ul>
  <li><%= obj.errors.full_messages.first %></li>
 </ul> 
</div>
 <% end %>

app/views/users/_form.html.erb
<div class="container">
<div class="row justify-content-center">
<div class="col-10">
<%= render "shared/errors", obj: @user %>
<%= form_with model: @user , class: "shadow p-3 mb-3 bg-info rounded" do |form| %>

  <div class="form-group row">
    <%= form.label :username , class: "col-2 col-form-label text-light"%>
    <div class="col-10">
    <%= form.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
    </div>
  </div>

  <div class="form-group row mt-4">
    <%= form.label :email , class: "col-2 col-form-label text-light"%>
    <div class="col-10">
    <%= form.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email address"  %>
    </div>
  </div>

    <div class="form-group row mt-4">
    <%= form.label :password , class: "col-2 col-form-label text-light"%>
    <div class="col-10">
    <%= form.password_field :password, class: "form-control shadow rounded", placeholder: "Choose a password"  %>
    </div>
  </div>

  <div class="form-group row mt-4 justify-content-center">
    <%= form.submit class: "btn btn-outline-light btn-lg w-25" %>
  </div>
 
<% end %>
</div>
<%#= link_to '[ Cancel and return to articles listing ]' , root_path , class: "text-info row justify-content-center text-decoration-none"%>
</div>
</div>

app/views/users/_user.html.erb
<div class="container">
<% @users.each do |user|%>
<div class="row justify-content-md-center">
<div class="col-8 mt-4">
<div class="card text-center shadow-lg mb-5 bg-white rounded">
  <div class="card-header font-italic">
     <%= link_to user.username, user %>
  </div>
  <div class="card-body">
    <h5 class="card-title">
    <%= link_to gravatar_for(user, size: 150), user %></h5>
    <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
    <%= link_to "View Profile", user_path(user), class: "btn btn-outline-primary" %>
    <%= link_to "Edit Profile", edit_user_path(user), class: "btn btn-outline-info" %>
  </div>
  <div class="card-footer text-muted">
    <small>Joined <%= time_ago_in_words(user.created_at)%> ago. 
    </small>
  </div>
</div>
</div>
</div>
<%end%> 
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Update your account</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<h1 class="text-center mt-4">All the bloggers</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for Alpha Blog</h1>

<%= render 'form'%>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s Profile</h1>

<%= gravatar_for @user, size: 200%>

<h3 class="text-center mt-4">Articles</h3>

<%= render 'articles/article'%>